# Generated by Django 4.2.20 on 2025-04-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://cleanplatesdetroit.com/data/meals/1289.jpg', max_length=500),
        ),
    ]
